apiVersion: backstage.io/v1alpha12
kind: Component
metadata:
  name: backstagearpit
  description: |
    Backstage Devx is an open-source developer portal that puts the developer experience first.
  links:
    - title: Website
      url: http://en.wikipedia.org/wiki/Main_Page
    - title: Documentation
      url: http://en.wikipedia.org/wiki/Main_Page
    - title: Storybook
      url: http://en.wikipedia.org/wiki/Main_Page
    - title: Discord Chat
      url: http://en.wikipedia.org/wiki/Main_Page
  annotations:
    github.com/project-slug: backstage/backstage
    backstage.io/techdocs-ref: url:http://en.wikipedia.org/wiki/Main_Page
    lighthouse.com/website-url: http://en.wikipedia.org/wiki/Main_Page
spec:
  type: library
  owner: CNCF
  lifecycle: experimental
